name: Workflow

on: [push]

jobs:
  tests:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-version: ['8.0', '8.1', '8.2', '8.3']
        prefer-lowest: [--prefer-lowest, '']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP with ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov

      - name: Check PHP Version
        run: php -v

      - name: Check Composer Version
        run: composer -V

      - name: Check PHP Extensions
        run: php -m

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer update --no-interaction --no-suggest ${{ matrix.prefer-lowest }}

      - name: Run test suite
        run: composer run test

      - name: Run psalm
        run: composer run psalm

      - name: CodeCov
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #required
          file: ./clover.xml #optional
