name: Workflow

on: [push]

jobs:
  tests:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-version: ['7.2', '7.3', '7.4']

    steps:
      - uses: actions/checkout@v1

      - name: Setup PHP ${{ matrix.php-version }}
        if: matrix.php-version != '7.4' && matrix.operating-system == 'ubuntu-latest'
        run: |
          sudo update-alternatives --set php /usr/bin/php${{ matrix.php-version }}
          sudo update-alternatives --set phar /usr/bin/phar${{ matrix.php-version }}
          sudo update-alternatives --set phpdbg /usr/bin/phpdbg${{ matrix.php-version }}
          sudo update-alternatives --set php-cgi /usr/bin/php-cgi${{ matrix.php-version }}
          sudo update-alternatives --set phar.phar /usr/bin/phar.phar${{ matrix.php-version }}

      - name: Setup PHP ${{ matrix.php-version }}
        if: matrix.php-version == '7.4' || matrix.operating-system != 'ubuntu-latest'
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov

      - name: Check PHP Version
        run: php -v

      - name: Check Composer Version
        run: composer -V

      - name: Check PHP Extensions
        run: php -m

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --no-interaction --no-suggest --ignore-platform-reqs

      - name: Run test suite
        run: composer run test

      - name: Run psalm
        run: composer run psalm

      - name: CodeCov
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #required
          file: ./clover.xml #optional
